[site]
title = "Yongxin Zhou"
description = "Postdoctoral Researcher at CNRS and Université Grenoble Alpes."
favicon = "/favicon.svg"
last_updated = "June 7, 2026"

[author]
name = "Yongxin Zhou"
title = "Postdoctoral Researcher"
institution = "CNRS / Grenoble Computer Science Laboratory (LIG)"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "yongxin.zhou@univ-grenoble-alpes.fr"
location = "Grenoble, France"
location_url = "https://www.liglab.fr/en"
location_details = [
  "Laboratoire Informatique de Grenoble (LIG),",
  "Université Grenoble Alpes, Grenoble, France"
]
google_scholar = "https://scholar.google.com/citations?user=hHkqPjgAAAAJ&hl=en"
github = "https://github.com/yongxin2020"
linkedin = "https://www.linkedin.com/in/yongxin-z-b71106167/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
